

FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt-get update && \
    apt-get install -y docker.io && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -g 968 dockerhost && \
    usermod -aG dockerhost jenkins

USER jenkins
